## Numpy

- Array from numpy

### Difference between array and list

## Array

- An array is a collection of homogenous data-types.
- 4 byte
- Array can store data very compactly and more effcient for storing large amount of data.
- Array are great for numerical operations, list cannot directly handle math operations
- As the array size increases, numpy array get around 30 times faster than python list.
- Because the numpy array is denely packed in memory due to homogeous type, also frees the memory faster.
- you have to explicity import nupy to use array

## List

- wheras list is a collection of hetrogeneous data-types
- 14 byte
- List less effcient than array for storing large amount of data.
- its is python data type

In [4]:
a=["sahil",1,2,True]
a

['sahil', 1, 2, True]

In [5]:
array=[1,2,3,5]
array

[1, 2, 3, 5]

In [64]:
import numpy as np

In [65]:
my_list=["ram",123,50.5,7+2j]
print(my_list)
type(my_list)
#Whereas list is a collection of hetrogeneous data-types

['ram', 123, 50.5, (7+2j)]


list

## Create array

In [66]:
a=np.array([[[1,2,3,6,9]]])
print(a)
type(a)

[[[1 2 3 6 9]]]


numpy.ndarray

In [67]:
a.ndim

3

## String > Complex > float > int

In [68]:
my_array=np.array(["ram",123,50.5,7+2j])
print(my_array)
type(my_array)
#An array is a collection of homogenous data-types.

['ram' '123' '50.5' '(7+2j)']


numpy.ndarray

In [69]:
x=np.array([123,"sahil","sayli",45.7])
print(x)
type(x)

['123' 'sahil' 'sayli' '45.7']


numpy.ndarray

In [70]:
x=np.array([123,2+4j,45.7,2])  #int,float,complex
print(x)
type(x)

[123. +0.j   2. +4.j  45.7+0.j   2. +0.j]


numpy.ndarray

In [71]:
my_array=np.array([123,50.5])
print(my_array)
type(my_array)

[123.   50.5]


numpy.ndarray

## Empty Numpy array

In [72]:
a=np.array([])
a

array([], dtype=float64)

## Attributes:

- ndarray.ndim: The number of dimensions (axes) of the array.
- ndarray.shape: A tuple representing the dimensions of the array, e.g., (rows, columns) for a 2D array.
- ndarray.size: The total number of elements in the array.
- ndarray.dtype: The data type of elements in the array.
- ndarray.itemsize: The size in bytes of each element in the array.
- ndarray.data: A buffer containing the actual elements of the array.

## 1.ndim

In [73]:
x=np.array([[123,"sahil","sayli",45.7],[1,2,3,4]])
print(x)

[['123' 'sahil' 'sayli' '45.7']
 ['1' '2' '3' '4']]


In [74]:
x.ndim

2

In [75]:
x=np.array([[123,45,45,60],[1,2,3,4],[10,20,30,12]])
print(x)

[[123  45  45  60]
 [  1   2   3   4]
 [ 10  20  30  12]]


## 2.Shape

In [76]:
x.shape

(3, 4)

## 3.Size

In [77]:
x.size

12

## 4.dtype

In [78]:
x.dtype

dtype('int32')

## 5.Itemsize

In [79]:
x.itemsize

4

In [80]:
x.data

## 6.DataType

In [81]:
a=np.array([[1,2,34],[1,2,3]])
print(a)

[[ 1  2 34]
 [ 1  2  3]]


In [82]:
a.dtype

dtype('int32')

In [83]:
a=np.array([[1,2,34],[1,2,3]],dtype=str)
print(a)

[['1' '2' '34']
 ['1' '2' '3']]


In [84]:
a=np.array([[1,2,34],[1,2,3]],dtype=complex)
print(a)

[[ 1.+0.j  2.+0.j 34.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j]]


## 7.Data

In [85]:
x.data

## Array Creation Function:

In [86]:
a_list=np.array([["a","b","c","d"],["x","y","z","p"]])
print(a_list)

[['a' 'b' 'c' 'd']
 ['x' 'y' 'z' 'p']]


In [87]:
b_tuple=np.array([("a","b","c","d"),("x","y","z","p")])
print(b_tuple)

[['a' 'b' 'c' 'd']
 ['x' 'y' 'z' 'p']]


In [88]:
b_tuple.shape

(2, 4)

## 2.np.zeros()

In [89]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3.zeros_like

In [90]:
a_list=np.array([[[1,2,3,6],[4,8,7,9],[4,8,9,7]]])
print(a_list)


[[[1 2 3 6]
  [4 8 7 9]
  [4 8 9 7]]]


In [91]:
a_list.ndim

3

In [92]:
np.zeros_like(a_list)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

## 4.ones()

In [93]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 5.ones_like

In [94]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)
y.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [95]:
np.ones_like(y)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 6np.empty()

In [96]:
np.empty(0)

array([], dtype=float64)

## 7.np.arange()

In [97]:
for i in range(1,19,3):   #range(start,stop,step)
    print(i)

1
4
7
10
13
16


In [98]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

## 8.nplinspace

In [101]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## 9.np.logspace()

In [100]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

## Array Manipulation Functions:

numpy.transpose: Transpose the array. numpy.flatten: Return a copy of the array collapsed into one dimension. numpy.concatenate: Join arrays along an existing axis. numpy.vstack: Stack arrays vertically (row-wise). numpy.hstack: Stack arrays horizontally (column-wise). numpy.split: Split an array into multiple sub-arrays along a specified axis. numpy.delete: Delete elements from an array. numpy.insert: Insert elements into an array. numpy.append: Append elements to the end of an array.

In [102]:
a_list=np.array([[1,2,3,6],[4,8,7,9],[4,8,9,7]])
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [103]:
#12=(2,6), (4,3), (12,1)

## 1.reshape()

In [104]:
a_list.reshape(6,2)

array([[1, 2],
       [3, 6],
       [4, 8],
       [7, 9],
       [4, 8],
       [9, 7]])

In [105]:
a_list.shape

(3, 4)

## 2.Transpose()

In [106]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
y.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## 3.concatinate()

In [108]:
np.concatenate(a_list)

array([1, 2, 3, 6, 4, 8, 7, 9, 4, 8, 9, 7])

In [109]:
np.concatenate(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

## v,h-stack()

In [111]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
np.vstack(y)   # v=vertical

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [113]:
np.hstack(y)   #h=horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [114]:
np.vstack(a_list)

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [116]:
np.hstack(a_list)

array([1, 2, 3, 6, 4, 8, 7, 9, 4, 8, 9, 7])

## 4.split()

In [118]:
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [119]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.split(e,(2))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

## 5.delete()

In [123]:
np.delete(e,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Mathematical Function:

- numpy.add: Element-wise addition.
- numpy.subtract: Element-wise subtraction.
- numpy.multiply: Element-wise multiplication.
- numpy.divide: Element-wise division.
- numpy.power: Element-wise exponentiation.
- numpy.sqrt: Square root of each element.
- numpy.sin, numpy.cos, numpy.tan: Trigonometric functions.
- numpy.exp: Exponential function.
- numpy.log, numpy.log10: Natural logarithm and base-10 logarithm.
- numpy.sum: Sum of all elements in an array.
- numpy.mean: Mean (average) of array elements.
- numpy.median: Median of array elements.
- numpy.min, 
- numpy.max: Minimum and maximum values in an array.

In [125]:
a_list

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [126]:
b_list=np.array([[10,20,30,40],[50,30,20,10],[60,70,40,30]])
b_list

array([[10, 20, 30, 40],
       [50, 30, 20, 10],
       [60, 70, 40, 30]])

In [127]:
np.add(a_list,b_list)

array([[11, 22, 33, 46],
       [54, 38, 27, 19],
       [64, 78, 49, 37]])

## sum()

In [128]:
b_list.sum()

410

## indexing and slicing

### indexing of 2D array

In [129]:
a=np.array([[5,2,34],[1,2,3]])
a.ndim

2

In [130]:
a[0][1]

2

In [131]:
a[1][0]

1

## Indexing of 3D array

## Creating Random numbers

In [132]:
import random

In [133]:
np.random.rand(3)

array([0.05814662, 0.05571357, 0.69412291])

In [134]:
np.random.rand(4,4)

array([[0.1576389 , 0.49793597, 0.75037725, 0.87278988],
       [0.40250235, 0.04266086, 0.02010157, 0.77925405],
       [0.80924116, 0.46120265, 0.84281815, 0.80415   ],
       [0.59817427, 0.02246031, 0.75600082, 0.35797517]])

In [135]:
a=np.random.rand(4,4,4)
print(a)
a.ndim

[[[0.52224336 0.10647843 0.60084297 0.58126725]
  [0.41812389 0.22548334 0.44644469 0.64771597]
  [0.31055693 0.26948263 0.92450332 0.58262786]
  [0.56489553 0.16417274 0.30398771 0.86215042]]

 [[0.65157027 0.41578321 0.80594184 0.38953925]
  [0.83254087 0.75599041 0.48223835 0.59849583]
  [0.91567468 0.66908965 0.8525117  0.57626889]
  [0.62681684 0.83025753 0.58027129 0.48646215]]

 [[0.31407401 0.04904883 0.8362037  0.70240173]
  [0.57842398 0.02058983 0.0119063  0.87721503]
  [0.12235554 0.21977229 0.03123205 0.46736087]
  [0.72880272 0.49391664 0.08140644 0.95440795]]

 [[0.97571023 0.01518948 0.81651324 0.33778027]
  [0.9703594  0.74091644 0.6922169  0.03435053]
  [0.80810137 0.93229015 0.99549633 0.59551243]
  [0.62146392 0.44410975 0.43161565 0.72030749]]]


3

In [136]:
a=np.random.rand(4,4,4,4)
print(a)
a.ndim

[[[[0.23285947 0.80128836 0.93070117 0.29061352]
   [0.50572514 0.86049945 0.68267849 0.93119324]
   [0.48357789 0.69603105 0.9355629  0.395628  ]
   [0.16440485 0.53214945 0.73479691 0.81001781]]

  [[0.64224462 0.78328941 0.01781377 0.1579409 ]
   [0.07153727 0.30077674 0.41312623 0.37750068]
   [0.6761554  0.26806621 0.29996349 0.856879  ]
   [0.26219624 0.5040888  0.63390762 0.67473979]]

  [[0.10482496 0.5180603  0.17804772 0.43571664]
   [0.21031495 0.22470576 0.12239187 0.96515772]
   [0.43970056 0.77592749 0.57731816 0.99687474]
   [0.92537874 0.78678534 0.80836701 0.5937821 ]]

  [[0.09517529 0.67103881 0.00625946 0.27890722]
   [0.04753645 0.30342476 0.66786363 0.92569515]
   [0.99890992 0.99860791 0.80977677 0.42990183]
   [0.25087322 0.81404174 0.99797026 0.375187  ]]]


 [[[0.08206025 0.76753299 0.95215264 0.11646196]
   [0.29560553 0.10464213 0.40750707 0.20539314]
   [0.32712289 0.07694594 0.37194135 0.65755086]
   [0.61559437 0.00789832 0.5310665  0.76560282]]

  [[0.20

4

In [140]:
np.random.randint(1,10,(5,2))

array([[1, 8],
       [7, 4],
       [9, 1],
       [3, 1],
       [9, 7]])

In [141]:
np.random.randint(1,100,(5,2))

array([[30, 10],
       [ 5, 16],
       [64, 19],
       [89, 41],
       [18, 91]])

## Reshape

In [145]:
a=np.random.randint(1,100,(5,10))
a

array([[63, 49, 65, 35, 96, 25, 66, 85, 83, 38],
       [91, 96, 58, 65, 39, 94, 90, 50,  5, 29],
       [53, 86,  4, 27, 25, 52, 80, 55, 47, 29],
       [91, 82, 74, 13, 27, 98, 91, 76, 81,  2],
       [30, 94, 13, 47, 15, 45, 14, 53,  5, 12]])

In [ ]:
50
50 * 1
25 * 2
10 * 5

In [147]:
b=a.reshape(25,2)
b

array([[63, 49],
       [65, 35],
       [96, 25],
       [66, 85],
       [83, 38],
       [91, 96],
       [58, 65],
       [39, 94],
       [90, 50],
       [ 5, 29],
       [53, 86],
       [ 4, 27],
       [25, 52],
       [80, 55],
       [47, 29],
       [91, 82],
       [74, 13],
       [27, 98],
       [91, 76],
       [81,  2],
       [30, 94],
       [13, 47],
       [15, 45],
       [14, 53],
       [ 5, 12]])

In [148]:
b=a.reshape(10,5)
b

array([[63, 49, 65, 35, 96],
       [25, 66, 85, 83, 38],
       [91, 96, 58, 65, 39],
       [94, 90, 50,  5, 29],
       [53, 86,  4, 27, 25],
       [52, 80, 55, 47, 29],
       [91, 82, 74, 13, 27],
       [98, 91, 76, 81,  2],
       [30, 94, 13, 47, 15],
       [45, 14, 53,  5, 12]])

In [149]:
a=np.random.randint(1,100,(1,100))
a

array([[16, 95, 94, 56, 96,  5, 33, 51,  7, 68, 95,  8, 26, 35, 50, 14,
        93, 64, 97, 12, 20, 65,  9, 51, 60, 58, 70, 66, 94, 96, 19, 32,
        82, 43, 10, 52, 60, 60, 72, 68, 17, 88, 39,  2, 66, 30, 33, 22,
        58, 51, 25, 36, 75,  3, 70, 37, 43, 18, 84,  3, 71, 87, 74, 80,
        35,  3, 35, 73, 86, 26, 66, 99, 41, 29,  3, 33, 17,  5, 89, 54,
        35, 74, 91, 96, 74, 78, 54, 22, 40, 67, 74,  4, 92, 87, 60, 83,
        12, 73, 43, 15]])

In [ ]:
10 * 10
25 * 4
50 * 2
100 * 1
20 * 5

In [150]:
b=a.reshape(5,20)
b

array([[16, 95, 94, 56, 96,  5, 33, 51,  7, 68, 95,  8, 26, 35, 50, 14,
        93, 64, 97, 12],
       [20, 65,  9, 51, 60, 58, 70, 66, 94, 96, 19, 32, 82, 43, 10, 52,
        60, 60, 72, 68],
       [17, 88, 39,  2, 66, 30, 33, 22, 58, 51, 25, 36, 75,  3, 70, 37,
        43, 18, 84,  3],
       [71, 87, 74, 80, 35,  3, 35, 73, 86, 26, 66, 99, 41, 29,  3, 33,
        17,  5, 89, 54],
       [35, 74, 91, 96, 74, 78, 54, 22, 40, 67, 74,  4, 92, 87, 60, 83,
        12, 73, 43, 15]])

## Zeros

In [151]:
# Return a new array of given shape and type, filled with zeros.

In [152]:
np.zeros((9))

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [153]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [154]:
np.zeros((9,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [155]:
np.zeros_like(b)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Ones

Return a new array of given shape and type, filled with ones.

In [156]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [157]:
np.ones_like(b)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Full

Return a new array of given shape and type, filled with fill_value.

In [158]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [159]:
np.full((4,8),"mS")

array([['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS'],
       ['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS'],
       ['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS'],
       ['mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS', 'mS']], dtype='<U2')

In [160]:
np.full_like(b,15)

array([[15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15]])

## eye

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [161]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [162]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [163]:
np.eye(10,k=3)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [164]:
np.eye(10,k=-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

## arange()

In [167]:
range(1,10)

range(1, 10)

In [168]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [169]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [170]:
list(range(1,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [171]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [173]:
np.arange(1,51).reshape(2,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

## LineSpace

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [175]:
np.linspace(1,100,30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [176]:
np.linspace(1,100,30, endpoint=False)

array([ 1. ,  4.3,  7.6, 10.9, 14.2, 17.5, 20.8, 24.1, 27.4, 30.7, 34. ,
       37.3, 40.6, 43.9, 47.2, 50.5, 53.8, 57.1, 60.4, 63.7, 67. , 70.3,
       73.6, 76.9, 80.2, 83.5, 86.8, 90.1, 93.4, 96.7])

In [177]:
np.linspace(1,100,30, endpoint=False,retstep=True)

(array([ 1. ,  4.3,  7.6, 10.9, 14.2, 17.5, 20.8, 24.1, 27.4, 30.7, 34. ,
        37.3, 40.6, 43.9, 47.2, 50.5, 53.8, 57.1, 60.4, 63.7, 67. , 70.3,
        73.6, 76.9, 80.2, 83.5, 86.8, 90.1, 93.4, 96.7]),
 3.3)

In [178]:
np.linspace(1,1000,70)

array([   1.        ,   15.47826087,   29.95652174,   44.43478261,
         58.91304348,   73.39130435,   87.86956522,  102.34782609,
        116.82608696,  131.30434783,  145.7826087 ,  160.26086957,
        174.73913043,  189.2173913 ,  203.69565217,  218.17391304,
        232.65217391,  247.13043478,  261.60869565,  276.08695652,
        290.56521739,  305.04347826,  319.52173913,  334.        ,
        348.47826087,  362.95652174,  377.43478261,  391.91304348,
        406.39130435,  420.86956522,  435.34782609,  449.82608696,
        464.30434783,  478.7826087 ,  493.26086957,  507.73913043,
        522.2173913 ,  536.69565217,  551.17391304,  565.65217391,
        580.13043478,  594.60869565,  609.08695652,  623.56521739,
        638.04347826,  652.52173913,  667.        ,  681.47826087,
        695.95652174,  710.43478261,  724.91304348,  739.39130435,
        753.86956522,  768.34782609,  782.82608696,  797.30434783,
        811.7826087 ,  826.26086957,  840.73913043,  855.21739

## Logspace

- Return numbers spaced evenly on a log scale.
- LOG-BASE10

In [179]:
np.logspace(1,100)

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

## Where

In [180]:
z=np.arange(3,50)
z

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [181]:
np.where(z>15)

#it gives position of that element wch satisfy the condition

(array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
       dtype=int64),)

In [183]:
np.where(z%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45], dtype=int64),)

In [184]:
np.where(z==6)

(array([3], dtype=int64),)

## Split

Split an array into multiple sub-arrays

In [185]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
np.split(e,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [187]:
np.split(e,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [188]:
a,b=np.split(e,2)

In [189]:
a

array([0, 1, 2, 3, 4])

In [190]:
b

array([5, 6, 7, 8, 9])

## Arithematic Operation in numpy

In [191]:
a=np.array([[1,2,10],[5,7,8]])
b=np.array([[10,20,7],[50,70,7]])

In [192]:
a

array([[ 1,  2, 10],
       [ 5,  7,  8]])

In [193]:
b

array([[10, 20,  7],
       [50, 70,  7]])

In [194]:
np.add(a,b)

array([[11, 22, 17],
       [55, 77, 15]])

In [195]:
np.subtract(a,b)

array([[ -9, -18,   3],
       [-45, -63,   1]])

In [196]:
np.multiply(a,b)

array([[ 10,  40,  70],
       [250, 490,  56]])

In [197]:
np.divide(a,b)

array([[0.1       , 0.1       , 1.42857143],
       [0.1       , 0.1       , 1.14285714]])

In [198]:
np.mod(a,b)

array([[1, 2, 3],
       [5, 7, 1]])

In [199]:
np.power(a,b)

array([[         1,    1048576,   10000000],
       [1296002393, 1187094929,    2097152]])

## Statistics

In [2]:
import numpy as np
s=np.array([[50,10,30],[500,100,300],[5,1,3]])
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [3]:
np.amin(s)

1

In [5]:
np.amax(s)

500

In [8]:
np.amax(s,axis=0)

array([500, 100, 300])

In [9]:
np.amax(s,axis=1)

array([ 50, 500,   5])

In [10]:
np.mean(s)

111.0

In [13]:
np.var(s)

26960.666666666668

In [14]:
np.std(s)

164.1970361080451

## Datatype

### The main several data types supported by NumPy Python are:
- np.bool_: This type is used to return boolean values like (True or False).
- np.int: It is the default type of integer and C-type long.
- intc: It is similar to C integer and it indicates 32 or 64 bit integer.
- intp: This type indicates for indexing.
- int8: By default its range value is -128 to 127.
- int16: It is a 16 bit integer and by default its range value is (-32768 to 32767).
- int32: it is for set 32-bit integer and the range value is (-2147483648 to 2147483647).
- int64: By default its value is set at (-9223372036854775808 to 9223372036854775807).
- uint8: It is a 8 bit integer and range value is (0 to 255).
- uint16: It is a 16 bit unsigned integer and range value is (0 to 65535).
- uint32: This is a unsigned integer with 32 bit and its value is (0 to 4294967295).
- uint64: It is a 8 byte unsigned integer and range value is (0 to 18446744073709551615).

In [15]:
a=np.array([2555])
a.dtype

dtype('int32')

In [16]:
a=np.array([12,2,3,6],dtype=np.float16)
a.dtype

dtype('float16')

In [17]:
a

array([12.,  2.,  3.,  6.], dtype=float16)

In [18]:
np.array(np.datetime64('1999-06-14'))

array('1999-06-14', dtype='datetime64[D]')

In [19]:
new=np.array([1.0,2.0,3.0])
new

array([1., 2., 3.])

In [20]:
b=np.array([1,2,3])

In [21]:
b.astype('str')

array(['1', '2', '3'], dtype='<U11')

In [22]:
b.astype('f')

array([1., 2., 3.], dtype=float32)

In [23]:
np.iinfo(np.int8).max

127

In [24]:
np.iinfo(np.int8).min

-128